### ISSUE TITLE
Hey TPE i though to update you on this as my console throwing out errors

### ISSUE THREAD

**Issue by WildCraftMCPE** [TPEimperialPE/Prisons#11]
ScoreHud just messed with plugin again and they have just Removed the Depends which is in your plugin for PrisonScore. In plugin.yml 

just though to let you know just in case. 
My Console was throwing out errors so this might need fixing 

i have fixed mine anyway now but if this is any help to you feel free to use

name: PrisonScore
version: 1.0.0
api: 3.0.0
main: TPE\PrisonScore\PrisonScore
author: TPE
description: Prison Plugin For Scores.
extensions:
  Core: '>=7.4'
virions:
- ScoreHub

**Comment by TPEimperialPE** [comment]
Would I be correct in saying this doesn't actually make the plugin work.

**Comment by WildCraftMCPE** [comment]
The prisonscore is already broken

**Comment by TPEimperialPE** [comment]
Yeah the thing breaking it is the php version servers

**Comment by TPEimperialPE** [comment]
Issue with the addon not the plugin itself.
