### ISSUE TITLE
More Prestiges

### ISSUE THREAD

**Issue by ErosionYT** [TPEimperialPE/Prisons#13]
Can you add more prestiges then just the 3?

**Comment by TPEimperialPE** [comment]
Yes simply add then within the config in the same format as the other
prestiges.

**Comment by ErosionYT** [comment]
tysm

**Comment by ErosionYT** [comment]
Can you also change the pres number to a roman numeral. eg pre 5 = pre V?

**Comment by ErosionYT** [comment]
along with making a pres multiplyer?
