### ISSUE TITLE
Giving rank to aplayer when /rankup

### ISSUE THREAD

**Issue by JohnnyX071** [TPEimperialPE/Prisons#2]
Hello, how can I give another rank to a player when he does /rankup so like if you are in mine A and you rank up you will be in mine B and when you talk in chan it will say Mine B instead of A

**Comment by TPEimperialPE** [comment]
In the pure chat configuration file use the tags {PRISON_RANK} and {PRISON_ASCENSION} in order to display the rank and ascension level of a player.
