### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ItzFel** [TPEimperialPE/Prisons#3]
![Screenshot_2021-01-05-18-28-54-347_com server auditor ssh client](https://user-images.githubusercontent.com/62336632/103635780-f97d9880-4f83-11eb-941a-5640fbd3a0f0.png)

**Comment by TPEimperialPE** [comment]
If anyone experiences this error let me know, I'll leave this issue open for a few days if anyone wishes to respond.

**Comment by TPEimperialPE** [comment]
Keep in mind I believe this was occuring as he was using a dev build.

**Comment by ItzFel** [comment]
it's not an error anymore it's my fault on PureChat

**Comment by ItzFel** [comment]
I want to ask, how are the letters capitalized? I use purechat and the letter is small not a capital "a"

**Comment by TPEimperialPE** [comment]
You need to go to the config for prisons and change the 'rankName' of each rank. By default it's 'a' not A.

**Comment by ItzFel** [comment]
![Screenshot_2021-01-06-17-02-55-942_com gbwhatsapp](https://user-images.githubusercontent.com/62336632/103749985-2a6fd300-5041-11eb-98c7-dcdf0b9f69c6.png)

still not capital letters

**Comment by TPEimperialPE** [comment]
Show me your config because it is working for me, also make sure you have the version of the plugin installed from poggit, not a dev build.

**Comment by ItzFel** [comment]
![Screenshot_2021-01-06-20-04-33-353_turbo client](https://user-images.githubusercontent.com/62336632/103767036-d70a7e80-505a-11eb-88d9-684f43658480.png)

**Comment by TPEimperialPE** [comment]
Hmm, restart your server.

**Comment by ItzFel** [comment]
still ._.

**Comment by TPEimperialPE** [comment]
Are you using the version from poggit https://poggit.pmmp.io/p/Prisons/1.0.0

Because I believe you were using a development build.

**Comment by ItzFel** [comment]
I use it from poggit and the letters are still small, not capitalized ._.

**Comment by TPEimperialPE** [comment]
I have no clue because I'm using the same version and it is working correctly for me, if this happens to other people I will look further into it. My only other suggestion is wrapping the 'A' in the config in "" so it is like this rankName: "A"

**Comment by ItzFel** [comment]
Can you accept my discord? Kevin.#4214

**Comment by TPEimperialPE** [comment]
I'm making a scorehud add-on for prisons which will half resolve this issue, I may also add a command where players can view each other's rank/ascension level.
