### ISSUE TITLE
Rebirth

### ISSUE THREAD

**Issue by ElementalMinecraftGaming** [TPEimperialPE/Prisons#5]
I suggest adding a rebirth option for when they ascend to the max so that they can restart from Mine A all over again

**Comment by TPEimperialPE** [comment]
That's basically what the prestige feature is.

**Comment by ElementalMinecraftGaming** [comment]
The prestige has a limit so it's not a rebirth, rebirth completely resets progress entirely

**Comment by TPEimperialPE** [comment]
That's basically pointless, if you wanna do that then just delete the
database.

**Comment by ElementalMinecraftGaming** [comment]
So delete the database every time a player ranks up and remove everyone else's progress?

**Comment by TPEimperialPE** [comment]
Bro there's no reason for me to add that feature, if the seasons you are
doing for prisons is long enough for players to complete prestiges then
that does not sound good. People will not play after rebirthing because
they've just basically lost all their progress.

**Comment by ElementalMinecraftGaming** [comment]
Fine i'll just remake it.

**Comment by TPEimperialPE** [comment]
You mean you'll fork it.

**Comment by ElementalMinecraftGaming** [comment]
Nah, i'm going to edit the source code and remake some it so that it fits my needs. 0-0

**Comment by TPEimperialPE** [comment]
Ok in my personal opinion that's an extreme feature but go ahead.

**Comment by ElementalMinecraftGaming** [comment]
Can't keep adding mines forever, need something to reset a player's mine progress. That's all i am gonna add as well as changing the prot for plot worlds to allow multiple because that is affecting my other worlds. XD

**Comment by TPEimperialPE** [comment]
You don't add more mines for prestiging, you should just get people mining
in the same mines for ranks, maybe adding a prestige mine once every 5
prestiges.
