### ISSUE TITLE
"/rankup" not doing anything

### ISSUE THREAD

**Issue by Kayoddik** [TPEimperialPE/Prisons#6]
Hi there.  I'm having an issue with /rankup working. When I type /rankup, nothing happens. no errors in the logs, just nothing happening. Also the {PRISON_RANK} won't display. it just shuffles through a bunch of characters. {PRISON_PRESTIGE} displays fine. This plugin sounds amazing! Any help getting it running right would be extremely appreciated.

**Comment by TPEimperialPE** [comment]
Can you DM me on discord?

**Comment by Kayoddik** [comment]
Yeah:) what's your discord?

**Comment by TPEimperialPE** [comment]
TPE#1061

**Comment by Kayoddik** [comment]
ok sent you a request:)
