### ISSUE TITLE
Hey TPE Can you take a look in to this

### ISSUE THREAD

**Issue by WildCraftMCPE** [TPEimperialPE/Prisons#8]
Am Having A issue that someone else did on here sometime back
hopefully you can help me becuase i really like using this plugin
plugin is from the website as normal Not a dev build.

Console Error

Warning: SQLite3::prepare(): Unable to prepare statement: 1, near "prisonrank": syntax error in phar://C:/Users/xtrmt/OneDrive/Desktop/Server/plugins/Prisons (4).phar/src/TPE/Prisons/libs/poggit/libasynql/sqlite3/Sqlite3Thread.php on line 79
[21:38:19] [Server thread/ERROR]: [Prisons] SQL PREPARE error: near "prisonrank": syntax error, for query UPDATE prisons_players
SET username='MegaCraft6994'
prisonrank='b',
prestige=0
WHERE uuid = '257de885-30b2-326d-9e44-f5d0ba5bca7d'; | []

**Comment by TPEimperialPE** [comment]
Hm

**Comment by TPEimperialPE** [comment]
Do you have scorehud installed

**Comment by WildCraftMCPE** [comment]
> Do you have scorehud installed

Yes I have scorehud installed 
I also have the prisonscore plugin for it 

I also noticed this happens when I do /rankup 
It works for scorehud and says B but for where people type is still says [A] then this error pops up in my Console

**Comment by TPEimperialPE** [comment]
Remove scorehud for now.

**Comment by TPEimperialPE** [comment]
Fixed
